/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Gilit
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        
        jTextAreaMain.setOpaque(false);
        jTextAreaMain.setBackground(new Color(0,0,0,0));
        
        jTextAreaMenu.setOpaque(false);
        jTextAreaMenu.setBackground(new Color(0,0,0,0));
        
        jScrollPane1.getViewport().setBackground(new Color(0,0,0,0));
        jScrollPane2.getViewport().setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMenu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMain = new javax.swing.JTextArea();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(976, 732));
        setSize(new java.awt.Dimension(976, 732));
        getContentPane().setLayout(null);

        jTextAreaMenu.setColumns(20);
        jTextAreaMenu.setRows(5);
        jTextAreaMenu.setAutoscrolls(false);
        jTextAreaMenu.setBorder(null);
        jTextAreaMenu.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaMenu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 180, 450);

        jTextAreaMain.setColumns(20);
        jTextAreaMain.setRows(5);
        jTextAreaMain.setBorder(null);
        jTextAreaMain.setOpaque(false);
        jScrollPane2.setViewportView(jTextAreaMain);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(248, 50, 690, 580);

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/main.png"))); // NOI18N
        jLabelBG.setMaximumSize(new java.awt.Dimension(976, 732));
        jLabelBG.setMinimumSize(new java.awt.Dimension(976, 732));
        getContentPane().add(jLabelBG);
        jLabelBG.setBounds(0, 0, 990, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMain;
    private javax.swing.JTextArea jTextAreaMenu;
    // End of variables declaration//GEN-END:variables
}
